### This file is auto generated by Puppet ###
### Manual changes will be overwritten    ###

#!/bin/bash

username=$1

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 username"
    echo "Replace username with an account that can join this machine to the domain"
    exit 1
fi

# join domain with the name provided
net ads join -U $username
authconfig --enablemkhomedir --enablewinbind --enablewinbindauth --update
