#!/bin/bash

### This file is auto generated by Puppet ###
### Manual changes will be overwritten    ###

if [ "$#" -eq 0 ] && [ -n "$PT_username" ] && [ -n "$PT_password" ]; then
    username="${PT_username}%${PT_password}"
elif [ "$#" eq 1 ]; then
    username=$1
else
    echo "Usage: $0 username"
    echo "Replace username with an account that can join this machine to the domain"
    echo "Alternatively, you can run this via the task provided in the winbind Puppet module"
    exit 1
fi

pam-config --add --winbind --mkhomedir --mkhomedir-umask=0077

# join domain with the name provided
net ads join -U ${username}
